### ISSUE TITLE
Add Spectator feature

### ISSUE THREAD

**Issue by mbottini** [PDX-Checkers/checkers#39]
For our demonstration, I was thinking about the following:

* We run the Checkers server in a Docker container on my home computer. It can be accessed from `http://pogtastic.asuscomm.com:3000`.

* We connect to the server with our own computers and start a game.

* The computer that's hooked up to the projector is a spectator and updates its board on every move.

* We give a neato lecture on websockets and game logic.

---

This would require the following from me:

* Create additional subscriber methods in the `ActiveGame` class to handle spectators.
* Create an additional data structure in the `ActiveGame` class to hold spectator userIDs.
* Add a couple more `JSONRequest`s to do the following:
    * Become a spectator of a game (`spectate_game`, takes a `gameID`, parsed by the `ActiveGameController`)
    * Leave a game (`leave_game`, parsed by the `ActiveGame`).
* add a `JSONResponse` to do the following:
    * Notify that you're spectating a game (as opposed to joining a game).

This would require the following from you:

* An additional dialog button to choose to spectate from a list of games instead of joining one.
* Logic to send and receive these additional WebSocket requests.
* A similar board instance as playing, except the player cannot make moves. Obviously, the server doesn't care if the user tries, as he can't; he's not subscribed to a listener that can make moves.

---

All of this is totally optional; if you have other stuff to do, we already have an MVP, and we're well past what Caterina is expecting. Everyone else's project is going to be a shitty little CRUD app to post TODOs or whatever. But if you want to keep working on it, I think this would be worthwhile.

**Comment by ryanclanigan** [comment]
Hell yeah lets do it.

**Comment by mbottini** [comment]
Done.
